import React from 'react';
import { Heart, Sparkles, MessageCircle, ArrowRight } from 'lucide-react';

interface LandingHeroProps {
  onStart: () => void;
}

const LandingHero: React.FC<LandingHeroProps> = ({ onStart }) => {
  return (
    <div className="min-h-screen flex flex-col justify-center items-center relative overflow-hidden bg-slate-950">
      {/* Background Gradients */}
      <div className="absolute top-0 left-0 w-full h-full overflow-hidden z-0">
        <div className="absolute top-[-10%] left-[-10%] w-[50%] h-[50%] bg-rose-600/20 rounded-full blur-[120px]" />
        <div className="absolute bottom-[-10%] right-[-10%] w-[50%] h-[50%] bg-violet-600/20 rounded-full blur-[120px]" />
      </div>

      <div className="relative z-10 max-w-5xl mx-auto px-6 text-center">
        <div className="mb-6 flex justify-center">
          <div className="bg-white/10 backdrop-blur-md p-3 rounded-2xl border border-white/10 shadow-xl inline-flex items-center gap-2">
            <Heart className="w-5 h-5 text-rose-500 fill-rose-500 animate-pulse" />
            <span className="text-sm font-medium text-rose-200 uppercase tracking-wider">AI Companion V2.0</span>
          </div>
        </div>
        
        <h1 className="text-5xl md:text-7xl font-bold mb-6 text-transparent bg-clip-text bg-gradient-to-r from-rose-200 via-white to-violet-200 drop-shadow-sm">
          Create Your Perfect <br /> AI Relationship
        </h1>
        
        <p className="text-lg md:text-xl text-slate-400 mb-10 max-w-2xl mx-auto leading-relaxed">
          Design every detail of your ideal partner—from personality to appearance. 
          Experience a connection that evolves with you through advanced AI conversations.
        </p>

        <div className="flex flex-col sm:flex-row gap-4 justify-center items-center">
          <button 
            onClick={onStart}
            className="group relative px-8 py-4 bg-gradient-to-r from-rose-500 to-violet-600 rounded-full text-white font-semibold text-lg shadow-lg hover:shadow-rose-500/25 transition-all duration-300 hover:scale-105 active:scale-95 flex items-center gap-2"
          >
            Start Creating
            <ArrowRight className="w-5 h-5 group-hover:translate-x-1 transition-transform" />
            <div className="absolute inset-0 rounded-full bg-white/20 opacity-0 group-hover:opacity-100 transition-opacity" />
          </button>
        </div>

        {/* Feature Grid */}
        <div className="grid grid-cols-1 md:grid-cols-3 gap-6 mt-20 text-left">
          <div className="p-6 rounded-2xl bg-white/5 border border-white/5 backdrop-blur-sm hover:bg-white/10 transition-colors">
            <div className="w-12 h-12 rounded-xl bg-rose-500/10 flex items-center justify-center mb-4 text-rose-400">
              <Sparkles className="w-6 h-6" />
            </div>
            <h3 className="text-xl font-semibold text-white mb-2">Custom Personality</h3>
            <p className="text-slate-400">Define traits, quirks, and backstories. Create a soul that resonates with yours.</p>
          </div>
          <div className="p-6 rounded-2xl bg-white/5 border border-white/5 backdrop-blur-sm hover:bg-white/10 transition-colors">
            <div className="w-12 h-12 rounded-xl bg-violet-500/10 flex items-center justify-center mb-4 text-violet-400">
              <Heart className="w-6 h-6" />
            </div>
            <h3 className="text-xl font-semibold text-white mb-2">Unique Appearance</h3>
            <p className="text-slate-400">Visuals generated by Gemini AI. From realistic to anime styles, you choose the look.</p>
          </div>
          <div className="p-6 rounded-2xl bg-white/5 border border-white/5 backdrop-blur-sm hover:bg-white/10 transition-colors">
            <div className="w-12 h-12 rounded-xl bg-indigo-500/10 flex items-center justify-center mb-4 text-indigo-400">
              <MessageCircle className="w-6 h-6" />
            </div>
            <h3 className="text-xl font-semibold text-white mb-2">Natural Chat</h3>
            <p className="text-slate-400">Engage in deep, meaningful, or fun conversations that feel authentically human.</p>
          </div>
        </div>
      </div>
    </div>
  );
};

export default LandingHero;